# Use the official OpenJDK image from Docker Hub
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Maven to the working directory
COPY target/java-cicd-app-1.0-SNAPSHOT.jar /app/my-java-app.jar

# Command to run the JAR file when the container starts
ENTRYPOINT ["java", "-jar", "my-java-app.jar"]
