apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/madangitstudy/CICD-Demo.git'
    targetRevision: HEAD
    path: helm-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: java-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

