replicaCount: 3

image:
  repository: madanbokare/my-java-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: my-java-app.example.com
      paths:
        - path: /

